JWT authorizaiton
mash-up-kr/TwoToo-Node pull request #16
Opened 2023-06-18 08:35 UTC by Hyun-git

## 🔥 관련 이슈

close #3 

## 🔥 PR Point

- User socialID, loginType 받게 설정
- 위의 정보를 비교해서 JWT 토큰 생성 후 반환
- JWT토큰을 통해 Authorization

## 🔥 To Reviewers

2023-06-20 05:28 UTC, seohyun0120 requested changes

2023-06-20 05:28 UTC, seohyun0120 commented on src/app.module.ts
> +      secret: 'dkTkghdtkaghkdlxld12341234',
이것도 새로 발급하고, .env로 분리합시다.

2023-06-20 05:28 UTC, seohyun0120 commented on src/app.module.ts
> +    ]),
UserModule에 import 되어있는데 중복으로 import해도 되나요?

2023-06-20 05:28 UTC, seohyun0120 commented on src/user/user.service.ts
> +    return this.userModel.findOne({socialId: socialId, loginType:loginType});
앞에 await 붙여주세요~

2023-06-20 07:26 UTC, LouiMinister commented on src/app.module.ts
> +    ]),
빼야할 것 같아요~

2023-06-20 07:26 UTC, LouiMinister commented on src/user/user.service.ts
> +      secret:'dkTkghdtkaghkdlxld12341234'
키 env로 빼야하지 않어?

2023-06-20 07:26 UTC, LouiMinister commented on src/auth/auth.guard.ts
> +  }
일케하면 controller에서 req.user 가 가지고 있는게 무엇인지 타입으로 확인 할 수 있나?

안되면 해야할 것 같아~! (Controller에서 사용할 Req타입 만들어서 모든 Controller에 적용하기)

2023-06-20 07:26 UTC, LouiMinister commented
수고했어~~ 👍

2023-06-20 07:37 UTC, Marades commented on src/auth/auth.guard.ts
> +  }
저거 verifyAsync 에 제네릭으로 타입 넘겨주면 추론 가능하게 돼

`verityAsync<UserPayload>` 이런 식으로

2023-06-20 10:17 UTC, seohyun0120 commented on src/auth/auth.guard.ts
> +  }
건회오빠 하이~

2023-06-20 10:35 UTC, Marades commented on src/auth/auth.guard.ts
> +  }
염탐왔지렁~

2023-06-20 13:31 UTC, Hyun-git commented on src/auth/auth.guard.ts
> +  }
req.user로 찍으면 contorller에서 사용 가능!

2023-06-20 14:53 UTC, seohyun0120 commented
lgtm 😃 고생했어!

2023-06-21 03:23 UTC, merged

2023-06-21 03:45 UTC, LouiMinister commented on src/auth/auth.guard.ts
> +  }
@Hyun-git 엉 쓸 수는 있는데 컨트롤러에서 req.user 찍으면 타입 추론이 안되가지고 건회형이 말한것 처럼 해줘야 할 것 같아

2023-06-21 06:04 UTC, LouiMinister commented on src/auth/auth.guard.ts
> +  }
@Hyun-git 
https://github.com/mash-up-kr/TwoToo-Node/pull/18
내가 했쏭~