feat: notification 기본 구조 설정
mash-up-kr/TwoToo-Node pull request #19
Opened 2023-06-22 02:05 UTC by Hyun-git

## 🔥 관련 이슈

close #11 

## 🔥 PR Point

- 클라이언트에서 받은 firebaseToken으로 푸시 알림을 보낸다
- 유저가 찌르기 요청을 보내면 현재 몇 번의 찌르기를 했는지 확인하고 찌르기가 가능하다면 push 알림과 DB에 저장한다.

## 🔥 To Reviewers

2023-06-22 06:15 UTC, LouiMinister commented on src/notification/notification.service.ts
> +  }
요런거 주석으로 // TODO: ~해야함 이런식으로 걸어두면 나중에 ide에서 찾기 편해가지공 해주면 좋아!

2023-06-22 06:15 UTC, LouiMinister approved these changes
LGTM

2023-06-22 10:15 UTC, Hyun-git commented on src/notification/notification.service.ts
> +  }
좋은 습관이군... 아직 습관을 들이지 못했어

2023-06-22 10:15 UTC, Hyun-git commented on src/notification/notification.service.ts
> +  }
와중에 회사껄로 commit 도ㅒㅆ네

2023-06-22 13:49 UTC, seohyun0120 requested changes

2023-06-22 13:49 UTC, seohyun0120 commented on src/challenge/challenge.service.ts
> +      throw new Error('No PartnerNo');
사소하지만 parterNo로 바꿨으면 합니당

2023-06-22 13:49 UTC, seohyun0120 commented on src/notification/schema/notification-counter.schema.ts
> +export class NotificationCounter {
NotificationCounter는 필요없어보임!
notification의 id값도 number type으로 관리할거면 counter를 만드는게 맞지만, 몽고가 자동 생성해주는 _id로 충분히 해결할 수 있어 보여~! notification 조회하거나 업데이트 할 일이 없어서 더더욱

2023-06-22 13:49 UTC, seohyun0120 commented on src/user/user.service.ts
> +  async getPartnerFirebaseToken({ userNo }: { userNo: number }) {
- 여기 파라미터 객체로 감싸주지 않아도 될 것 같아
- 리턴 타입 추가해주세요

2023-06-22 13:49 UTC, seohyun0120 commented on src/notification/notification.controller.ts
> +    const firebaseToken = await this.userService.getPartnerFirebaseToken({ userNo });
파트너의 토큰을 조회하는거면 userNo가 아니고 partnerNo여야되는거 아니야?

2023-06-22 14:31 UTC, Hyun-git commented on src/notification/notification.controller.ts
> +    const firebaseToken = await this.userService.getPartnerFirebaseToken({ userNo });
PartnerNo를 UserNo로 가져와야 하니까!

2023-06-22 14:32 UTC, Hyun-git commented on src/challenge/challenge.service.ts
> +      throw new Error('No PartnerNo');
Partner가 아닌 parter..?

2023-06-22 14:48 UTC, LouiMinister commented on src/notification/notification.controller.ts
> +    const firebaseToken = await this.userService.getPartnerFirebaseToken({ userNo });
헷갈릴 수는 있겠네

37번라인 변수명을 partnerFirebaseToken으로 하면 좀 더 가독성엔 좋겠다!

2023-06-23 04:01 UTC, seohyun0120 commented on src/challenge/challenge.service.ts
> +      throw new Error('No PartnerNo');
아 ㅋㅋ 대문자를 소문자로 바꾸자는 이야기였어 
오타! ㅋㅋㅋ

2023-06-23 04:06 UTC, seohyun0120 commented on src/notification/notification.controller.ts
> +    const firebaseToken = await this.userService.getPartnerFirebaseToken({ userNo });
내가 코드 이해를 잘못 했나? 
`getPartnerFirebaseToken()` 함수보면 userNo로 유저 조회해서 해당 유저의 firebaseToken을 가져오는 것 같은데!!

userNo로 partnerNo 가져오고, partnerNo로 유저 조회해서 firebaseToken 가져와야하는거 아닌가?!

2023-06-23 08:32 UTC, LouiMinister commented on src/notification/notification.controller.ts
> +    const firebaseToken = await this.userService.getPartnerFirebaseToken({ userNo });
@seohyun0120 메서드 이름 보면 파트너의 파이어베이스 토큰 가져오는거라 유저No를 넘기는 것 같아.
내 No -> Partner의 토큰

2023-06-25 06:04 UTC, merged